// Authentication

export const LOGIN_USER = 'LOGIN_USER'
export const LOGOUT_USER = 'LOGOUT_USER'


// User

export const SET_USER_INFO = "SET_USER_INFO"
export const REMOVE_USER_INFO = "REMOVE_USER_INFO"
export const CHANGE_PROFILE_PHOTO = "CHANGE_PROFILE_PHOTO"

// Board

export const MAKE_NEW_BOARD = 'MAKE_NEW_BOARD'
export const FETCH_ALL_BOARDS = 'FETCH_ALL_BOARDS'
export const FETCH_A_BOARD = 'FETCH_A_BOARD'
export const DELETE_BOARD = 'DELETE_BOARD'

// List

export const FETCH_ALL_LIST_WITH_CARDS = 'FETCH_ALL_LIST_WITH_CARDS'
export const CREATE_NEW_LIST = 'CREATE_NEW_LIST'
export const DELETE_LIST = 'DELETE_LIST'
export const CREATE_NEW_CARD = 'CREATE_NEW_CARD'
export const DELETE_CARD = 'DELETE_CARD'


// Card

export const FETCH_CARD = 'FETCH_CARD'
export const PUT_DESC = 'PUT_DESC'
export const SHUT_DOWN_CARD = 'SHUT_DOWN_CARD'

// CheckLists
export const FETCH_CHECKLISTS = 'FETCH_CHECKLISTS'
export const TOGGLE_CHECKLIST = 'TOGGLE_CHECKLIST'
export const CHANGE_CONTENT = 'CHANGE_CONTENT'
export const DELETE_CHECKLIST = 'DELETE_CHECKLIST'
export const POST_NEW_CHECKLIST = 'POST_NEW_CHECKLIST'

// Comment 

export const FETCH_COMMENTS = 'FETCH_COMMENTS'
export const POST_COMMENT = 'POST_COMMENT'
export const DELETE_COMMENT = 'DELETE_COMMENT'


// Change profile

export const CHANGE_PROFILE_TRUE = 'CHANGE_PROFILE_TRUE'
export const CHANGE_PROFILE_FALSE = 'CHANGE_PROFILE_FALSE'

// AddNewTeamForm

export const TURN_ADD_NEW_TEAM_FORM_ON = 'TURN_ADD_NEW_TEAM_FORM_ON'
export const TURN_ADD_NEW_TEAM_FORM_DOWN = 'TURN_ADD_NEW_TEAM_FORM_DOWN'