// Authentication

export const LOGIN_USER = 'LOGIN_USER'
export const LOGOUT_USER = 'LOGOUT_USER'


// User

export const SET_USER_INFO = "SET_USER_INFO"
export const REMOVE_USER_INFO = "REMOVE_USER_INFO"
export const CHANGE_PROFILE_PHOTO = "CHANGE_PROFILE_PHOTO"
export const ACCEPT_INVITATION = 'ACCEPT_INVITATION'
export const UPDATE_USER_PASSWORD = 'UPDATE_USER_PASSWORD'


// Board

export const MAKE_NEW_BOARD = 'MAKE_NEW_BOARD'
export const FETCH_ALL_BOARDS = 'FETCH_ALL_BOARDS'
export const FETCH_A_BOARD = 'FETCH_A_BOARD'
export const DELETE_BOARD = 'DELETE_BOARD'

// List

export const FETCH_ALL_LIST_WITH_CARDS = 'FETCH_ALL_LIST_WITH_CARDS'
export const CREATE_NEW_LIST = 'CREATE_NEW_LIST'
export const DELETE_LIST = 'DELETE_LIST'
export const CREATE_NEW_CARD = 'CREATE_NEW_CARD'
export const DELETE_CARD = 'DELETE_CARD'


// Card

export const FETCH_CARD = 'FETCH_CARD'
export const PUT_DESC = 'PUT_DESC'
export const SHUT_DOWN_CARD = 'SHUT_DOWN_CARD'

// CheckLists
export const FETCH_CHECKLISTS = 'FETCH_CHECKLISTS'
export const TOGGLE_CHECKLIST = 'TOGGLE_CHECKLIST'
export const CHANGE_CONTENT = 'CHANGE_CONTENT'
export const DELETE_CHECKLIST = 'DELETE_CHECKLIST'
export const POST_NEW_CHECKLIST = 'POST_NEW_CHECKLIST'

// Comment 

export const FETCH_COMMENTS = 'FETCH_COMMENTS'
export const POST_COMMENT = 'POST_COMMENT'
export const DELETE_COMMENT = 'DELETE_COMMENT'


// Change profile

export const CHANGE_PROFILE_TRUE = 'CHANGE_PROFILE_TRUE'
export const CHANGE_PROFILE_FALSE = 'CHANGE_PROFILE_FALSE'

// AddNewTeamForm

export const TURN_ADD_NEW_TEAM_FORM_ON = 'TURN_ADD_NEW_TEAM_FORM_ON'
export const TURN_ADD_NEW_TEAM_FORM_DOWN = 'TURN_ADD_NEW_TEAM_FORM_DOWN'


// Team
export const FETCH_TEAMS = 'FETCH_TEAMS'
export const POST_NEW_TEAM = 'POST_NEW_TEAM'
export const FETCH_A_TEAM = 'FETCH_A_TEAM'
export const INVITE_NEW_MEMBER = 'INVITE_NEW_MEMBER'
export const CREATE_NEW_TEAM_BOARD = 'CREATE_NEW_TEAM_BOARD'
export const CHANGE_TEAM_PHOTO = 'CHANGE_TEAM_PHOTO'

// CreateNewTeamBoard

export const TURN_ON_CREATE_NEW_TEAM_BOARD = 'TURN_ON_CREATE_NEW_TEAM_BOARD'
export const TURN_DOWN_CREATE_NEW_TEAM_BOARD = 'TURN_DOWN_CREATE_NEW_TEAM_BOARD'

// Notification
export const FETCH__UNREAD_NOTIFICATIONS_NUMBER = 'FETCH__UNREAD_NOTIFICATIONS_NUMBER'
export const FETCH_ALL_NOTIFICATIONS = 'FETCH_ALL_NOTIFICATIONS'
export const READ_ALL_NOTIFICATIONS = 'READ_ALL_NOTIFICATIONS'
export const DELETE_NOTIFICATION = 'DELETE_NOTIFICATION'
export const DELETE_ALL_NOTIFICATIONS = 'DELETE_ALL_NOTIFICATIONS'
export const ADD_NUMBER_ONE_UNREAD_NOTIFICATION = 'ADD_NUMBER_ONE_UNREAD_NOTIFICATION'


// Invitations

export const TURN_ON_INVITATION = 'TURN_ON_INVITATION'
export const TURN_DOWN_INVITATION = 'TURN_DOWN_INVITATION'


// TeamPhotoChangeForm

export const TURN_ON_TEAM_PHOTO_CHANGE_FORM = 'TURN_ON_TEAM_PHOTO_CHANGE_FORM'
export const TURN_DOWN_TEAM_PHOTO_CHANGE_FORM = 'TURN_DOWN_TEAM_PHOTO_CHANGE_FORM'

// NewPasswordFrom 

export const TURN_NEW_PASSWORD_FORM = 'TURN_NEW_PASSWORD_FORM'
export const TURN_NEW_PASSWORD_FORM_DOWN = 'TURN_NEW_PASSWORD_FORM_DOWN'